version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.18
    container_name: prodvault
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - private-volume:/vault/file:rw
      - ./vault/vault.json:/vault/config/vault.json:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json

volumes:
  private-volume:

