name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: 'Checkout GitHub repository'
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'  # Using Temurin as the distribution

      # Step 3: Check Java Version
      - name: 'Check Java Version'
        run: java -version

      # Step 4: Run SonarQube Scan
      - name: 'Run SonarQube Scan'
        id: sonar_scan  # Add an ID to this step to reference it later
        uses: sonarsource/sonarqube-scan-action@v3
        with:
          projectBaseDir: "."
          args: >
            -Dsonar.projectKey=azure-project
            -Dsonar.projectName="azure-project"  
            -Dsonar.projectVersion=1.0
            -Dsonar.java.binaries=**/target/classes
            -Dsonar.java.source=17  
            -Dsonar.java.target=17  
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}  # Fixed missing closing bracket

      # Step 5: Fetch the Analysis ID
      - name: 'Fetch Analysis ID'
        id: fetch_analysis_id
        run: |
          # Use the SonarQube API to fetch the latest analysis for the project
          curl -u "secrets.SONAR_TOKEN" "SONAR_HOST_URL/api/project_analyses/search?project=azure-project" | jq -r '.analyses[0].key'

      # Step 6: Check SonarQube Quality Gate Status
      - name: 'Check SonarQube Quality Gate Status'
        run: |
          # Use the environment variable to check the Quality Gate status
          RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?analysesId=${{ env.ANALYSIS_ID }}")
          echo "API Response: $RESPONSE"  # Debugging line
          # Check the status
          STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status')
          if [ "$STATUS" != "OK" ]; then
            echo "Quality Gate failed: $STATUS"
            exit 1
          fi
          echo "Quality Gate passed: $STATUS"

      # Step 7: Login to Azure CLI
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 8: Build and tag the Docker image with a timestamp
      - name: 'Build and Submit Image'
        id: build
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          IMAGE_URI=${{ secrets.ACR_LOGIN_SERVER }}/my-app:$TIMESTAMP
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV  # Store timestamp for later use
          
          # Build the Docker image
          docker build -t $IMAGE_URI .
          # Log in to ACR
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          # Push the Docker image to ACR
          docker push $IMAGE_URI

      # Step 9: Set up kubectl and configure AKS credentials
      - name: 'Set up kubectl'
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      # Step 10: Update the deployment file to use the new image tag    
      - name: 'Update Deployment Image'      
        run: |        
          sed -i "s|image: .*|image: ${{ secrets.ACR_LOGIN_SERVER }}/my-app:${{ env.TIMESTAMP }}|g" deployment.yaml    

      # Step 11: Apply the deployment file to the AKS cluster    
      - name: 'Deploy to AKS'      
        run: |        
          kubectl apply -f deployment.yaml
