name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: 'Checkout GitHub repository'
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'  # Using Temurin as the distribution

      # Step 3: Check Java Version
      - name: 'Check Java Version'
        run: java -version

      # Step 4: Run SonarQube Scan
      - name: 'Run SonarQube Scan'
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          projectBaseDir: "."
          args: >
            -Dsonar.projectKey=azure-project
            -Dsonar.projectName="azure-project"   
            -Dsonar.projectVersion=1.0
            -Dsonar.java.binaries=**/target/classes  
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

      # Step 5: Login to Azure CLI
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 6: Build and tag the Docker image with a timestamp
      - name: Build and Submit Image
        id: build
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          IMAGE_URI=${{ secrets.ACR_LOGIN_SERVER }}/my-app:$TIMESTAMP
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV  # Store timestamp for later use
          
          # Build the Docker image
          docker build -t $IMAGE_URI .
          # Log in to ACR
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          # Push the Docker image to ACR
          docker push $IMAGE_URI

      # Step 7: Set up kubectl and configure AKS credentials
      - name: 'Set up kubectl'
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}   

      # Step 8: Update the deployment file to use the new image tag    
      - name: 'Update Deployment Image'      
        run: |        
          sed -i "s|image: .*|image: ${{ secrets.ACR_LOGIN_SERVER }}/my-app:${{ env.TIMESTAMP }}|g" deployment.yaml    

      # Step 9: Apply the deployment file to the AKS cluster    
      - name: 'Deploy to AKS'      
        run: |        
          kubectl apply -f deployment.yaml
